CREATE TABLE IF NOT EXISTS BOARD (
    BOARD_ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE            VARCHAR(200) NOT NULL,
    CONTENT          CLOB NOT NULL,
    AUTHOR           VARCHAR(50) NOT NULL,
    CREATED_DATE     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_DATE     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VIEW_COUNT       INT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS IDX_BOARD_CREATED_DATE ON BOARD(CREATED_DATE DESC);
